// X-Macro file to generate Unicode Script pages mapping
//

ES_UNICODE_SCRIPTMAP_BEGIN
ES_UNICODE_SCRIPTMAP_ENTRY( Control_character                             , 0x0000, 0x001F, "Control character")
ES_UNICODE_SCRIPTMAP_ENTRY( Basic_Latin                                   , 0x0020, 0x007F, "Basic Latin")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_1_Supplement                            , 0x0080, 0x00FF, "Latin-1 Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_Extended_A                              , 0x0100, 0x017F, "Latin Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_Extended_B                              , 0x0180, 0x024F, "Latin Extended-B")
ES_UNICODE_SCRIPTMAP_ENTRY( IPA_Extensions                                , 0x0250, 0x02AF, "IPA Extensions")
ES_UNICODE_SCRIPTMAP_ENTRY( Spacing_Modifier_Letters                      , 0x02B0, 0x02FF, "Spacing Modifier Letters")
ES_UNICODE_SCRIPTMAP_ENTRY( Combining_Diacritical_Marks                   , 0x0300, 0x036F, "Combining Diacritical Marks")
ES_UNICODE_SCRIPTMAP_ENTRY( Greek_and_Coptic                              , 0x0370, 0x03FF, "Greek and Coptic")
ES_UNICODE_SCRIPTMAP_ENTRY( Cyrillic                                      , 0x0400, 0x04FF, "Cyrillic")
ES_UNICODE_SCRIPTMAP_ENTRY( Cyrillic_Supplement                           , 0x0500, 0x052F, "Cyrillic Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Armenian                                      , 0x0530, 0x058F, "Armenian")
ES_UNICODE_SCRIPTMAP_ENTRY( Hebrew                                        , 0x0590, 0x05FF, "Hebrew")
ES_UNICODE_SCRIPTMAP_ENTRY( Arabic                                        , 0x0600, 0x06FF, "Arabic")
ES_UNICODE_SCRIPTMAP_ENTRY( Syriac                                        , 0x0700, 0x074F, "Syriac")
ES_UNICODE_SCRIPTMAP_ENTRY( Arabic_Supplement                             , 0x0750, 0x077F, "Arabic Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Thaana                                        , 0x0780, 0x07BF, "Thaana")
ES_UNICODE_SCRIPTMAP_ENTRY( NKo                                           , 0x07C0, 0x07FF, "NKo")
ES_UNICODE_SCRIPTMAP_ENTRY( Samaritan                                     , 0x0800, 0x083F, "Samaritan")
ES_UNICODE_SCRIPTMAP_ENTRY( Mandaic                                       , 0x0840, 0x085F, "Mandaic")
ES_UNICODE_SCRIPTMAP_ENTRY( Syriac_Supplement                             , 0x0860, 0x086F, "Syriac Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Arabic_Extended_A                             , 0x08A0, 0x08FF, "Arabic Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Devanagari                                    , 0x0900, 0x097F, "Devanagari")
ES_UNICODE_SCRIPTMAP_ENTRY( Bengali                                       , 0x0980, 0x09FF, "Bengali")
ES_UNICODE_SCRIPTMAP_ENTRY( Gurmukhi                                      , 0x0A00, 0x0A7F, "Gurmukhi")
ES_UNICODE_SCRIPTMAP_ENTRY( Gujarati                                      , 0x0A80, 0x0AFF, "Gujarati")
ES_UNICODE_SCRIPTMAP_ENTRY( Oriya                                         , 0x0B00, 0x0B7F, "Oriya")
ES_UNICODE_SCRIPTMAP_ENTRY( Tamil                                         , 0x0B80, 0x0BFF, "Tamil")
ES_UNICODE_SCRIPTMAP_ENTRY( Telugu                                        , 0x0C00, 0x0C7F, "Telugu")
ES_UNICODE_SCRIPTMAP_ENTRY( Kannada                                       , 0x0C80, 0x0CFF, "Kannada")
ES_UNICODE_SCRIPTMAP_ENTRY( Malayalam                                     , 0x0D00, 0x0D7F, "Malayalam")
ES_UNICODE_SCRIPTMAP_ENTRY( Sinhala                                       , 0x0D80, 0x0DFF, "Sinhala")
ES_UNICODE_SCRIPTMAP_ENTRY( Thai                                          , 0x0E00, 0x0E7F, "Thai")
ES_UNICODE_SCRIPTMAP_ENTRY( Lao                                           , 0x0E80, 0x0EFF, "Lao")
ES_UNICODE_SCRIPTMAP_ENTRY( Tibetan                                       , 0x0F00, 0x0FFF, "Tibetan")
ES_UNICODE_SCRIPTMAP_ENTRY( Myanmar                                       , 0x1000, 0x109F, "Myanmar")
ES_UNICODE_SCRIPTMAP_ENTRY( Georgian                                      , 0x10A0, 0x10FF, "Georgian")
ES_UNICODE_SCRIPTMAP_ENTRY( Hangul_Jamo                                   , 0x1100, 0x11FF, "Hangul Jamo")
ES_UNICODE_SCRIPTMAP_ENTRY( Ethiopic                                      , 0x1200, 0x137F, "Ethiopic")
ES_UNICODE_SCRIPTMAP_ENTRY( Ethiopic_Supplement                           , 0x1380, 0x139F, "Ethiopic Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Cherokee                                      , 0x13A0, 0x13FF, "Cherokee")
ES_UNICODE_SCRIPTMAP_ENTRY( Unified_Canadian_Aboriginal_Syllabics         , 0x1400, 0x167F, "Unified Canadian Aboriginal Syllabics")
ES_UNICODE_SCRIPTMAP_ENTRY( Ogham                                         , 0x1680, 0x169F, "Ogham")
ES_UNICODE_SCRIPTMAP_ENTRY( Runic                                         , 0x16A0, 0x16FF, "Runic")
ES_UNICODE_SCRIPTMAP_ENTRY( Tagalog                                       , 0x1700, 0x171F, "Tagalog")
ES_UNICODE_SCRIPTMAP_ENTRY( Hanunoo                                       , 0x1720, 0x173F, "Hanunoo")
ES_UNICODE_SCRIPTMAP_ENTRY( Buhid                                         , 0x1740, 0x175F, "Buhid")
ES_UNICODE_SCRIPTMAP_ENTRY( Tagbanwa                                      , 0x1760, 0x177F, "Tagbanwa")
ES_UNICODE_SCRIPTMAP_ENTRY( Khmer                                         , 0x1780, 0x17FF, "Khmer")
ES_UNICODE_SCRIPTMAP_ENTRY( Mongolian                                     , 0x1800, 0x18AF, "Mongolian")
ES_UNICODE_SCRIPTMAP_ENTRY( Unified_Canadian_Aboriginal_Syllabics_Extended, 0x18B0, 0x18FF, "Unified Canadian Aboriginal Syllabics Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( Limbu                                         , 0x1900, 0x194F, "Limbu")
ES_UNICODE_SCRIPTMAP_ENTRY( Tai_Le                                        , 0x1950, 0x197F, "Tai Le")
ES_UNICODE_SCRIPTMAP_ENTRY( New_Tai_Lue                                   , 0x1980, 0x19DF, "New Tai Lue")
ES_UNICODE_SCRIPTMAP_ENTRY( Khmer_Symbols                                 , 0x19E0, 0x19FF, "Khmer Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Buginese                                      , 0x1A00, 0x1A1F, "Buginese")
ES_UNICODE_SCRIPTMAP_ENTRY( Tai_Tham                                      , 0x1A20, 0x1AAF, "Tai Tham")
ES_UNICODE_SCRIPTMAP_ENTRY( Combining_Diacritical_Marks_Extended          , 0x1AB0, 0x1AFF, "Combining Diacritical Marks Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( Balinese                                      , 0x1B00, 0x1B7F, "Balinese")
ES_UNICODE_SCRIPTMAP_ENTRY( Sundanese                                     , 0x1B80, 0x1BBF, "Sundanese")
ES_UNICODE_SCRIPTMAP_ENTRY( Batak                                         , 0x1BC0, 0x1BFF, "Batak")
ES_UNICODE_SCRIPTMAP_ENTRY( Lepcha                                        , 0x1C00, 0x1C4F, "Lepcha")
ES_UNICODE_SCRIPTMAP_ENTRY( Ol_Chiki                                      , 0x1C50, 0x1C7F, "Ol Chiki")
ES_UNICODE_SCRIPTMAP_ENTRY( Cyrillic_Extended_C                           , 0x1C80, 0x1C8F, "Cyrillic Extended C")
ES_UNICODE_SCRIPTMAP_ENTRY( Sundanese_Supplement                          , 0x1CC0, 0x1CCF, "Sundanese Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Vedic_Extensions                              , 0x1CD0, 0x1CFF, "Vedic Extensions")
ES_UNICODE_SCRIPTMAP_ENTRY( Phonetic_Extensions                           , 0x1D00, 0x1D7F, "Phonetic Extensions")
ES_UNICODE_SCRIPTMAP_ENTRY( Phonetic_Extensions_Supplement                , 0x1D80, 0x1DBF, "Phonetic Extensions Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Combining_Diacritical_Marks_Supplement        , 0x1DC0, 0x1DFF, "Combining Diacritical Marks Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_Extended_Additional                     , 0x1E00, 0x1EFF, "Latin Extended Additional")
ES_UNICODE_SCRIPTMAP_ENTRY( Greek_Extended                                , 0x1F00, 0x1FFF, "Greek Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( General_Punctuation                           , 0x2000, 0x206F, "General Punctuation")
ES_UNICODE_SCRIPTMAP_ENTRY( Superscripts_and_Subscripts                   , 0x2070, 0x209F, "Superscripts and Subscripts")
ES_UNICODE_SCRIPTMAP_ENTRY( Currency_Symbols                              , 0x20A0, 0x20CF, "Currency Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Combining_Diacritical_Marks_for_Symbols       , 0x20D0, 0x20FF, "Combining Diacritical Marks for Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Letterlike_Symbols                            , 0x2100, 0x214F, "Letterlike Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Number_Forms                                  , 0x2150, 0x218F, "Number Forms")
ES_UNICODE_SCRIPTMAP_ENTRY( Arrows                                        , 0x2190, 0x21FF, "Arrows")
ES_UNICODE_SCRIPTMAP_ENTRY( Mathematical_Operators                        , 0x2200, 0x22FF, "Mathematical Operators")
ES_UNICODE_SCRIPTMAP_ENTRY( Miscellaneous_Technical                       , 0x2300, 0x23FF, "Miscellaneous Technical")
ES_UNICODE_SCRIPTMAP_ENTRY( Control_Pictures                              , 0x2400, 0x243F, "Control Pictures")
ES_UNICODE_SCRIPTMAP_ENTRY( Optical_Character_Recognition                 , 0x2440, 0x245F, "Optical Character Recognition")
ES_UNICODE_SCRIPTMAP_ENTRY( Enclosed_Alphanumerics                        , 0x2460, 0x24FF, "Enclosed Alphanumerics")
ES_UNICODE_SCRIPTMAP_ENTRY( Box_Drawing                                   , 0x2500, 0x257F, "Box Drawing")
ES_UNICODE_SCRIPTMAP_ENTRY( Block_Elements                                , 0x2580, 0x259F, "Block Elements")
ES_UNICODE_SCRIPTMAP_ENTRY( Geometric_Shapes                              , 0x25A0, 0x25FF, "Geometric Shapes")
ES_UNICODE_SCRIPTMAP_ENTRY( Miscellaneous_Symbols                         , 0x2600, 0x26FF, "Miscellaneous Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Dingbats                                      , 0x2700, 0x27BF, "Dingbats")
ES_UNICODE_SCRIPTMAP_ENTRY( Miscellaneous_Mathematical_Symbols_A          , 0x27C0, 0x27EF, "Miscellaneous Mathematical Symbols-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Supplemental_Arrows_A                         , 0x27F0, 0x27FF, "Supplemental Arrows-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Braille_Patterns                              , 0x2800, 0x28FF, "Braille Patterns")
ES_UNICODE_SCRIPTMAP_ENTRY( Supplemental_Arrows_B                         , 0x2900, 0x297F, "Supplemental Arrows-B")
ES_UNICODE_SCRIPTMAP_ENTRY( Miscellaneous_Mathematical_Symbols_B          , 0x2980, 0x29FF, "Miscellaneous Mathematical Symbols-B")
ES_UNICODE_SCRIPTMAP_ENTRY( Supplemental_Mathematical_Operators           , 0x2A00, 0x2AFF, "Supplemental Mathematical Operators")
ES_UNICODE_SCRIPTMAP_ENTRY( Miscellaneous_Symbols_and_Arrows              , 0x2B00, 0x2BFF, "Miscellaneous Symbols and Arrows")
ES_UNICODE_SCRIPTMAP_ENTRY( Glagolitic                                    , 0x2C00, 0x2C5F, "Glagolitic")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_Extended_C                              , 0x2C60, 0x2C7F, "Latin Extended-C")
ES_UNICODE_SCRIPTMAP_ENTRY( Coptic                                        , 0x2C80, 0x2CFF, "Coptic")
ES_UNICODE_SCRIPTMAP_ENTRY( Georgian_Supplement                           , 0x2D00, 0x2D2F, "Georgian Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Tifinagh                                      , 0x2D30, 0x2D7F, "Tifinagh")
ES_UNICODE_SCRIPTMAP_ENTRY( Ethiopic_Extended                             , 0x2D80, 0x2DDF, "Ethiopic Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( Cyrillic_Extended_A                           , 0x2DE0, 0x2DFF, "Cyrillic Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Supplemental_Punctuation                      , 0x2E00, 0x2E7F, "Supplemental Punctuation")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Radicals_Supplement                       , 0x2E80, 0x2EFF, "CJK Radicals Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Kangxi_Radicals                               , 0x2F00, 0x2FDF, "Kangxi Radicals")
ES_UNICODE_SCRIPTMAP_ENTRY( Ideographic_Description_Characters            , 0x2FF0, 0x2FFF, "Ideographic Description Characters")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Symbols_and_Punctuation                   , 0x3000, 0x303F, "CJK Symbols and Punctuation")
ES_UNICODE_SCRIPTMAP_ENTRY( Hiragana                                      , 0x3040, 0x309F, "Hiragana")
ES_UNICODE_SCRIPTMAP_ENTRY( Katakana                                      , 0x30A0, 0x30FF, "Katakana")
ES_UNICODE_SCRIPTMAP_ENTRY( Bopomofo                                      , 0x3100, 0x312F, "Bopomofo")
ES_UNICODE_SCRIPTMAP_ENTRY( Hangul_Compatibility_Jamo                     , 0x3130, 0x318F, "Hangul Compatibility Jamo")
ES_UNICODE_SCRIPTMAP_ENTRY( Kanbun                                        , 0x3190, 0x319F, "Kanbun")
ES_UNICODE_SCRIPTMAP_ENTRY( Bopomofo_Extended                             , 0x31A0, 0x31BF, "Bopomofo Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Strokes                                   , 0x31C0, 0x31EF, "CJK Strokes")
ES_UNICODE_SCRIPTMAP_ENTRY( Katakana_Phonetic_Extensions                  , 0x31F0, 0x31FF, "Katakana Phonetic Extensions")
ES_UNICODE_SCRIPTMAP_ENTRY( Enclosed_CJK_Letters_and_Months               , 0x3200, 0x32FF, "Enclosed CJK Letters and Months")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Compatibility                             , 0x3300, 0x33FF, "CJK Compatibility")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs_Extension_A            , 0x3400, 0x4DBF, "CJK Unified Ideographs Extension A")
ES_UNICODE_SCRIPTMAP_ENTRY( Yijing_Hexagram_Symbols                       , 0x4DC0, 0x4DFF, "Yijing Hexagram Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs                        , 0x4E00, 0x9FFF, "CJK Unified Ideographs")
ES_UNICODE_SCRIPTMAP_ENTRY( Yi_Syllables                                  , 0xA000, 0xA48F, "Yi Syllables")
ES_UNICODE_SCRIPTMAP_ENTRY( Yi_Radicals                                   , 0xA490, 0xA4CF, "Yi Radicals")
ES_UNICODE_SCRIPTMAP_ENTRY( Lisu                                          , 0xA4D0, 0xA4FF, "Lisu")
ES_UNICODE_SCRIPTMAP_ENTRY( Vai                                           , 0xA500, 0xA63F, "Vai")
ES_UNICODE_SCRIPTMAP_ENTRY( Cyrillic_Extended_B                           , 0xA640, 0xA69F, "Cyrillic Extended-B")
ES_UNICODE_SCRIPTMAP_ENTRY( Bamum                                         , 0xA6A0, 0xA6FF, "Bamum")
ES_UNICODE_SCRIPTMAP_ENTRY( Modifier_Tone_Letters                         , 0xA700, 0xA71F, "Modifier Tone Letters")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_Extended_D                              , 0xA720, 0xA7FF, "Latin Extended-D")
ES_UNICODE_SCRIPTMAP_ENTRY( Syloti_Nagri                                  , 0xA800, 0xA82F, "Syloti Nagri")
ES_UNICODE_SCRIPTMAP_ENTRY( Common_Indic_Number_Forms                     , 0xA830, 0xA83F, "Common Indic Number Forms")
ES_UNICODE_SCRIPTMAP_ENTRY( Phags_pa                                      , 0xA840, 0xA87F, "Phags-pa")
ES_UNICODE_SCRIPTMAP_ENTRY( Saurashtra                                    , 0xA880, 0xA8DF, "Saurashtra")
ES_UNICODE_SCRIPTMAP_ENTRY( Devanagari_Extended                           , 0xA8E0, 0xA8FF, "Devanagari Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( Kayah_Li                                      , 0xA900, 0xA92F, "Kayah Li")
ES_UNICODE_SCRIPTMAP_ENTRY( Rejang                                        , 0xA930, 0xA95F, "Rejang")
ES_UNICODE_SCRIPTMAP_ENTRY( Hangul_Jamo_Extended_A                        , 0xA960, 0xA97F, "Hangul Jamo Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Javanese                                      , 0xA980, 0xA9DF, "Javanese")
ES_UNICODE_SCRIPTMAP_ENTRY( Myanmar_Extended_B                            , 0xA9E0, 0xA9FF, "Myanmar Extended-B")
ES_UNICODE_SCRIPTMAP_ENTRY( Cham                                          , 0xAA00, 0xAA5F, "Cham")
ES_UNICODE_SCRIPTMAP_ENTRY( Myanmar_Extended_A                            , 0xAA60, 0xAA7F, "Myanmar Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Tai_Viet                                      , 0xAA80, 0xAADF, "Tai Viet")
ES_UNICODE_SCRIPTMAP_ENTRY( Meetei_Mayek_Extensions                       , 0xAAE0, 0xAAFF, "Meetei Mayek Extensions")
ES_UNICODE_SCRIPTMAP_ENTRY( Ethiopic_Extended_A                           , 0xAB00, 0xAB2F, "Ethiopic Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Latin_Extended_E                              , 0xAB30, 0xAB6F, "Latin Extended-E")
ES_UNICODE_SCRIPTMAP_ENTRY( Cherokee_Supplement                           , 0xAB70, 0xABBF, "Cherokee Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Meetei_Mayek                                  , 0xABC0, 0xABFF, "Meetei Mayek")
ES_UNICODE_SCRIPTMAP_ENTRY( Hangul_Syllables                              , 0xAC00, 0xD7AF, "Hangul Syllables")
ES_UNICODE_SCRIPTMAP_ENTRY( Hangul_Jamo_Extended_B                        , 0xD7B0, 0xD7FF, "Hangul Jamo Extended-B")
ES_UNICODE_SCRIPTMAP_ENTRY( High_Surrogates                               , 0xD800, 0xDB7F, "High Surrogates")
ES_UNICODE_SCRIPTMAP_ENTRY( High_Private_Use_Surrogates                   , 0xDB80, 0xDBFF, "High Private Use Surrogates")
ES_UNICODE_SCRIPTMAP_ENTRY( Low_Surrogates                                , 0xDC00, 0xDFFF, "Low Surrogates")
ES_UNICODE_SCRIPTMAP_ENTRY( Private_Use_Area                              , 0xE000, 0xF8FF, "Private Use Area")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Compatibility_Ideographs                  , 0xF900, 0xFAFF, "CJK Compatibility Ideographs")
ES_UNICODE_SCRIPTMAP_ENTRY( Alphabetic_Presentation_Forms                 , 0xFB00, 0xFB4F, "Alphabetic Presentation Forms")
ES_UNICODE_SCRIPTMAP_ENTRY( Arabic_Presentation_Forms_A                   , 0xFB50, 0xFDFF, "Arabic Presentation Forms-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Variation_Selectors                           , 0xFE00, 0xFE0F, "Variation Selectors")
ES_UNICODE_SCRIPTMAP_ENTRY( Vertical_Forms                                , 0xFE10, 0xFE1F, "Vertical Forms")
ES_UNICODE_SCRIPTMAP_ENTRY( Combining_Half_Marks                          , 0xFE20, 0xFE2F, "Combining Half Marks")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Compatibility_Forms                       , 0xFE30, 0xFE4F, "CJK Compatibility Forms")
ES_UNICODE_SCRIPTMAP_ENTRY( Small_Form_Variants                           , 0xFE50, 0xFE6F, "Small Form Variants")
ES_UNICODE_SCRIPTMAP_ENTRY( Arabic_Presentation_Forms_B                   , 0xFE70, 0xFEFF, "Arabic Presentation Forms-B")
ES_UNICODE_SCRIPTMAP_ENTRY( Halfwidth_and_Fullwidth_Forms                 , 0xFF00, 0xFFEF, "Halfwidth and Fullwidth Forms")
ES_UNICODE_SCRIPTMAP_ENTRY( Specials                                      , 0xFFF0, 0xFFFF, "Specials")
ES_UNICODE_SCRIPTMAP_ENTRY( Linear_B_Syllabary                            , 0x10000, 0x1007F, "Linear B Syllabary")
ES_UNICODE_SCRIPTMAP_ENTRY( Linear_B_Ideograms                            , 0x10080, 0x100FF, "Linear B Ideograms")
ES_UNICODE_SCRIPTMAP_ENTRY( Aegean_Numbers                                , 0x10100, 0x1013F, "Aegean Numbers")
ES_UNICODE_SCRIPTMAP_ENTRY( Ancient_Greek_Numbers                         , 0x10140, 0x1018F, "Ancient Greek Numbers")
ES_UNICODE_SCRIPTMAP_ENTRY( Ancient_Symbols                               , 0x10190, 0x101CF, "Ancient Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Phaistos_Disc                                 , 0x101D0, 0x101FF, "Phaistos Disc")
ES_UNICODE_SCRIPTMAP_ENTRY( Lycian                                        , 0x10280, 0x1029F, "Lycian")
ES_UNICODE_SCRIPTMAP_ENTRY( Carian                                        , 0x102A0, 0x102DF, "Carian")
ES_UNICODE_SCRIPTMAP_ENTRY( Coptic_Epact_Numbers                          , 0x102E0, 0x102FF, "Coptic Epact Numbers")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_Italic                                    , 0x10300, 0x1032F, "Old Italic")
ES_UNICODE_SCRIPTMAP_ENTRY( Gothic                                        , 0x10330, 0x1034F, "Gothic")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_Permic                                    , 0x10350, 0x1037F, "Old Permic")
ES_UNICODE_SCRIPTMAP_ENTRY( Ugaritic                                      , 0x10380, 0x1039F, "Ugaritic")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_Persian                                   , 0x103A0, 0x103DF, "Old Persian")
ES_UNICODE_SCRIPTMAP_ENTRY( Deseret                                       , 0x10400, 0x1044F, "Deseret")
ES_UNICODE_SCRIPTMAP_ENTRY( Shavian                                       , 0x10450, 0x1047F, "Shavian")
ES_UNICODE_SCRIPTMAP_ENTRY( Osmanya                                       , 0x10480, 0x104AF, "Osmanya")
ES_UNICODE_SCRIPTMAP_ENTRY( Osage                                         , 0x104B0, 0x104FF, "Osage")
ES_UNICODE_SCRIPTMAP_ENTRY( Elbasan                                       , 0x10500, 0x1052F, "Elbasan")
ES_UNICODE_SCRIPTMAP_ENTRY( Caucasian_Albanian                            , 0x10530, 0x1056F, "Caucasian Albanian")
ES_UNICODE_SCRIPTMAP_ENTRY( Linear_A                                      , 0x10600, 0x1077F, "Linear A")
ES_UNICODE_SCRIPTMAP_ENTRY( Cypriot_Syllabary                             , 0x10800, 0x1083F, "Cypriot Syllabary")
ES_UNICODE_SCRIPTMAP_ENTRY( Imperial_Aramaic                              , 0x10840, 0x1085F, "Imperial Aramaic")
ES_UNICODE_SCRIPTMAP_ENTRY( Palmyrene                                     , 0x10860, 0x1087F, "Palmyrene")
ES_UNICODE_SCRIPTMAP_ENTRY( Nabataean                                     , 0x10880, 0x108AF, "Nabataean")
ES_UNICODE_SCRIPTMAP_ENTRY( Hatran                                        , 0x108E0, 0x108FF, "Hatran")
ES_UNICODE_SCRIPTMAP_ENTRY( Phoenician                                    , 0x10900, 0x1091F, "Phoenician")
ES_UNICODE_SCRIPTMAP_ENTRY( Lydian                                        , 0x10920, 0x1093F, "Lydian")
ES_UNICODE_SCRIPTMAP_ENTRY( Meroitic_Hieroglyphs                          , 0x10980, 0x1099F, "Meroitic Hieroglyphs")
ES_UNICODE_SCRIPTMAP_ENTRY( Meroitic_Cursive                              , 0x109A0, 0x109FF, "Meroitic Cursive")
ES_UNICODE_SCRIPTMAP_ENTRY( Kharoshthi                                    , 0x10A00, 0x10A5F, "Kharoshthi")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_South_Arabian                             , 0x10A60, 0x10A7F, "Old South Arabian")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_North_Arabian                             , 0x10A80, 0x10A9F, "Old North Arabian")
ES_UNICODE_SCRIPTMAP_ENTRY( Manichaean                                    , 0x10AC0, 0x10AFF, "Manichaean")
ES_UNICODE_SCRIPTMAP_ENTRY( Avestan                                       , 0x10B00, 0x10B3F, "Avestan")
ES_UNICODE_SCRIPTMAP_ENTRY( Inscriptional_Parthian                        , 0x10B40, 0x10B5F, "Inscriptional Parthian")
ES_UNICODE_SCRIPTMAP_ENTRY( Inscriptional_Pahlavi                         , 0x10B60, 0x10B7F, "Inscriptional Pahlavi")
ES_UNICODE_SCRIPTMAP_ENTRY( Psalter_Pahlavi                               , 0x10B80, 0x10BAF, "Psalter Pahlavi")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_Turkic                                    , 0x10C00, 0x10C4F, "Old Turkic")
ES_UNICODE_SCRIPTMAP_ENTRY( Old_Hungarian                                 , 0x10C80, 0x10CFF, "Old Hungarian")
ES_UNICODE_SCRIPTMAP_ENTRY( Rumi_Numeral_Symbols                          , 0x10E60, 0x10E7F, "Rumi Numeral Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Brahmi                                        , 0x11000, 0x1107F, "Brahmi")
ES_UNICODE_SCRIPTMAP_ENTRY( Kaithi                                        , 0x11080, 0x110CF, "Kaithi")
ES_UNICODE_SCRIPTMAP_ENTRY( Sora_Sompeng                                  , 0x110D0, 0x110FF, "Sora Sompeng")
ES_UNICODE_SCRIPTMAP_ENTRY( Chakma                                        , 0x11100, 0x1114F, "Chakma")
ES_UNICODE_SCRIPTMAP_ENTRY( Mahajani                                      , 0x11150, 0x1117F, "Mahajani")
ES_UNICODE_SCRIPTMAP_ENTRY( Sharada                                       , 0x11180, 0x111DF, "Sharada")
ES_UNICODE_SCRIPTMAP_ENTRY( Sinhala_Archaic_Numbers                       , 0x111E0, 0x111FF, "Sinhala Archaic Numbers")
ES_UNICODE_SCRIPTMAP_ENTRY( Khojki                                        , 0x11200, 0x1124F, "Khojki")
ES_UNICODE_SCRIPTMAP_ENTRY( Multani                                       , 0x11280, 0x112AF, "Multani")
ES_UNICODE_SCRIPTMAP_ENTRY( Khudawadi                                     , 0x112B0, 0x112FF, "Khudawadi")
ES_UNICODE_SCRIPTMAP_ENTRY( Grantha                                       , 0x11300, 0x1137F, "Grantha")
ES_UNICODE_SCRIPTMAP_ENTRY( Newa                                          , 0x11400, 0x1147F, "Newa")
ES_UNICODE_SCRIPTMAP_ENTRY( Tirhuta                                       , 0x11480, 0x114DF, "Tirhuta")
ES_UNICODE_SCRIPTMAP_ENTRY( Siddham                                       , 0x11580, 0x115FF, "Siddham")
ES_UNICODE_SCRIPTMAP_ENTRY( Modi                                          , 0x11600, 0x1165F, "Modi")
ES_UNICODE_SCRIPTMAP_ENTRY( Mongolian_Supplement                          , 0x11660, 0x1167F, "Mongolian Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Takri                                         , 0x11680, 0x116CF, "Takri")
ES_UNICODE_SCRIPTMAP_ENTRY( Ahom                                          , 0x11700, 0x1173F, "Ahom")
ES_UNICODE_SCRIPTMAP_ENTRY( Warang_Citi                                   , 0x118A0, 0x118FF, "Warang Citi")
ES_UNICODE_SCRIPTMAP_ENTRY( Zanabazar_Square                              , 0x11A00, 0x11A4F, "Zanabazar Square")
ES_UNICODE_SCRIPTMAP_ENTRY( Soyombo                                       , 0x11A50, 0x11AAF, "Soyombo")
ES_UNICODE_SCRIPTMAP_ENTRY( Pau_Cin_Hau                                   , 0x11AC0, 0x11AFF, "Pau Cin Hau")
ES_UNICODE_SCRIPTMAP_ENTRY( Bhaiksuki                                     , 0x11C00, 0x11C6F, "Bhaiksuki")
ES_UNICODE_SCRIPTMAP_ENTRY( Marchen                                       , 0x11C70, 0x11CBF, "Marchen")
ES_UNICODE_SCRIPTMAP_ENTRY( Masaram_Gondi                                 , 0x11D00, 0x11D5F, "Masaram Gondi")
ES_UNICODE_SCRIPTMAP_ENTRY( Cuneiform                                     , 0x12000, 0x123FF, "Cuneiform")
ES_UNICODE_SCRIPTMAP_ENTRY( Cuneiform_Numbers_and_Punctuation             , 0x12400, 0x1247F, "Cuneiform Numbers and Punctuation")
ES_UNICODE_SCRIPTMAP_ENTRY( Early_Dynastic_Cuneiform                      , 0x12480, 0x1254F, "Early Dynastic Cuneiform")
ES_UNICODE_SCRIPTMAP_ENTRY( Egyptian_Hieroglyphs                          , 0x13000, 0x1342F, "Egyptian Hieroglyphs")
ES_UNICODE_SCRIPTMAP_ENTRY( Anatolian_Hieroglyphs                         , 0x14400, 0x1467F, "Anatolian Hieroglyphs")
ES_UNICODE_SCRIPTMAP_ENTRY( Bamum_Supplement                              , 0x16800, 0x16A3F, "Bamum Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Mro                                           , 0x16A40, 0x16A6F, "Mro")
ES_UNICODE_SCRIPTMAP_ENTRY( Bassa_Vah                                     , 0x16AD0, 0x16AFF, "Bassa Vah")
ES_UNICODE_SCRIPTMAP_ENTRY( Pahawh_Hmong                                  , 0x16B00, 0x16B8F, "Pahawh Hmong")
ES_UNICODE_SCRIPTMAP_ENTRY( Miao                                          , 0x16F00, 0x16F9F, "Miao")
ES_UNICODE_SCRIPTMAP_ENTRY( Ideographic_Symbols_and_Punctuation           , 0x16FE0, 0x16FFF, "Ideographic Symbols and Punctuation")
ES_UNICODE_SCRIPTMAP_ENTRY( Tangut                                        , 0x17000, 0x187FF, "Tangut")
ES_UNICODE_SCRIPTMAP_ENTRY( Tangut_Components                             , 0x18800, 0x18AFF, "Tangut Components")
ES_UNICODE_SCRIPTMAP_ENTRY( Kana_Supplement                               , 0x1B000, 0x1B0FF, "Kana Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Kana_Extended_A                               , 0x1B100, 0x1B12F, "Kana Extended-A")
ES_UNICODE_SCRIPTMAP_ENTRY( Nushu                                         , 0x1B170, 0x1B2FF, "Nushu")
ES_UNICODE_SCRIPTMAP_ENTRY( Duployan                                      , 0x1BC00, 0x1BC9F, "Duployan")
ES_UNICODE_SCRIPTMAP_ENTRY( Shorthand_Format_Controls                     , 0x1BCA0, 0x1BCAF, "Shorthand Format Controls")
ES_UNICODE_SCRIPTMAP_ENTRY( Byzantine_Musical_Symbols                     , 0x1D000, 0x1D0FF, "Byzantine Musical Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Musical_Symbols                               , 0x1D100, 0x1D1FF, "Musical Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Ancient_Greek_Musical_Notation                , 0x1D200, 0x1D24F, "Ancient Greek Musical Notation")
ES_UNICODE_SCRIPTMAP_ENTRY( Tai_Xuan_Jing_Symbols                         , 0x1D300, 0x1D35F, "Tai Xuan Jing Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Counting_Rod_Numerals                         , 0x1D360, 0x1D37F, "Counting Rod Numerals")
ES_UNICODE_SCRIPTMAP_ENTRY( Mathematical_Alphanumeric_Symbols             , 0x1D400, 0x1D7FF, "Mathematical Alphanumeric Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Sutton_SignWriting                            , 0x1D800, 0x1DAAF, "Sutton SignWriting")
ES_UNICODE_SCRIPTMAP_ENTRY( Glagolitic_Supplement                         , 0x1E000, 0x1E02F, "Glagolitic Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Mende_Kikakui                                 , 0x1E800, 0x1E8DF, "Mende Kikakui")
ES_UNICODE_SCRIPTMAP_ENTRY( Adlam                                         , 0x1E900, 0x1E95F, "Adlam")
ES_UNICODE_SCRIPTMAP_ENTRY( Arabic_Mathematical_Alphabetic_Symbols        , 0x1EE00, 0x1EEFF, "Arabic Mathematical Alphabetic Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Mahjong_Tiles                                 , 0x1F000, 0x1F02F, "Mahjong Tiles")
ES_UNICODE_SCRIPTMAP_ENTRY( Domino_Tiles                                  , 0x1F030, 0x1F09F, "Domino Tiles")
ES_UNICODE_SCRIPTMAP_ENTRY( Playing_Cards                                 , 0x1F0A0, 0x1F0FF, "Playing Cards")
ES_UNICODE_SCRIPTMAP_ENTRY( Enclosed_Alphanumeric_Supplement              , 0x1F100, 0x1F1FF, "Enclosed Alphanumeric Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Enclosed_Ideographic_Supplement               , 0x1F200, 0x1F2FF, "Enclosed Ideographic Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Miscellaneous_Symbols_and_Pictographs         , 0x1F300, 0x1F5FF, "Miscellaneous Symbols and Pictographs")
ES_UNICODE_SCRIPTMAP_ENTRY( Emoticons                                     , 0x1F600, 0x1F64F, "Emoticons (Emoji)")
ES_UNICODE_SCRIPTMAP_ENTRY( Ornamental_Dingbats                           , 0x1F650, 0x1F67F, "Ornamental Dingbats")
ES_UNICODE_SCRIPTMAP_ENTRY( Transport_and_Map_Symbols                     , 0x1F680, 0x1F6FF, "Transport and Map Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Alchemical_Symbols                            , 0x1F700, 0x1F77F, "Alchemical Symbols")
ES_UNICODE_SCRIPTMAP_ENTRY( Geometric_Shapes_Extended                     , 0x1F780, 0x1F7FF, "Geometric Shapes Extended")
ES_UNICODE_SCRIPTMAP_ENTRY( Supplemental_Arrows_C                         , 0x1F800, 0x1F8FF, "Supplemental Arrows-C")
ES_UNICODE_SCRIPTMAP_ENTRY( Supplemental_Symbols_and_Pictographs          , 0x1F900, 0x1F9FF, "Supplemental Symbols and Pictographs")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs_Extension_B            , 0x20000, 0x2A6DF, "CJK Unified Ideographs Extension B")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs_Extension_C            , 0x2A700, 0x2B73F, "CJK Unified Ideographs Extension C")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs_Extension_D            , 0x2B740, 0x2B81F, "CJK Unified Ideographs Extension D")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs_Extension_E            , 0x2B820, 0x2CEAF, "CJK Unified Ideographs Extension E")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Unified_Ideographs_Extension_F            , 0x2CEB0, 0x2EBEF, "CJK Unified Ideographs Extension F")
ES_UNICODE_SCRIPTMAP_ENTRY( CJK_Compatibility_Ideographs_Supplement       , 0x2F800, 0x2FA1F, "CJK Compatibility Ideographs Supplement")
ES_UNICODE_SCRIPTMAP_ENTRY( Tags                                          , 0xE0000, 0xE007F, "Tags")
ES_UNICODE_SCRIPTMAP_ENTRY( Variation_Selectors_Supplement                , 0xE0100, 0xE01EF, "Variation Selectors Supplement")
ES_UNICODE_SCRIPTMAP_END

#undef ES_UNICODE_SCRIPTMAP_BEGIN
#undef ES_UNICODE_SCRIPTMAP_END
#undef ES_UNICODE_SCRIPTMAP_ENTRY
